@startmindmap

+ <font size=45> 🤔     </font> 
-+ Mi huella digital
-++ Interacciones con IA
-++ En redes sociales
-++ Identidad digital y Web3
-++ Huella de carbono digital
++ Tecnologías transformadoras
+++ IA generativa y sistemas autónomos
+++ Computación cuántica
+++ Web3 y blockchain
+++ Metaverso y realidad extendida
+++ Internet de los sentidos
+++ Gemelos digitales
+++ Sostenibilidad digital

@endmindmap