@startuml

class "CEO\nChief Executive Officer" as CEO {
  +definirVisiónEmpresarial()
  +supervisarOperaciones()
}

' Primera línea de reporte
class "COO\nChief Operating Officer" as COO{
  +gestionarOperaciones()
  +ejecutarEstrategia()
}

class "CFO\nChief Financial Officer" as CFO{
  +gestionarFinanzas()
  +planificarPresupuesto()
  +gestionarRiesgosFinancieros()
}

class "CMO\nChief Marketing Officer" as CMO{
  +desarrollarEstrategiaMarketing()
  +gestionarMarca()
}

' Paquetes por áreas funcionales
package "Tecnología e información" {
  class "CIO\nChief Information Officer" as CIO{
    +definirEstrategiaInformación()
    +mejorarEficienciaOperativa()
  }
  
  class "CTO\nChief Technology Officer" as CTO{
    +desarrollarTecnología()
    +implementarSolucionesTécnicas()
  }
  
  class "CISO\nChief Information Security Officer" as CISO{
    +gestionarSeguridad()
    +supervisarCumplimientoNormativo()
  }
  
  class "CDO\nChief Digital Officer" as CDO{
    +liderarTransformaciónDigital()
    +integrarTecnologías()
  }
  
  class "CDO\nChief Data Officer" as CDataO{
    +definirEstrategiaDatos()
    +establecerGobernanzaDatos()
  }
  
  class "CAO\nChief Analytics Officer" as CAO{
    +desarrollarEstrategiaAnalítica()
    +generarInformesEstratégicos()
  }
}

package "Experiencia y comunicación" {
  class "CCO\nChief Communications Officer" as CCO{
    +definirEstrategiaComunicación()
    +posicionarMarca()
  }
  
  class "CXO\nChief Experience Officer" as CXO{
    +mejorarExperienciaCliente()
    +gestionarJornadaCliente()
  }
  
  class "CGO\nChief Growth Officer" as CGO{
    +diseñarEstrategiaCrecimiento()
    +expandirMercados()
  }
  
  class "CPO\nChief Product Officer" as CPO{
    +definirEstrategiaProducto()
    +desarrollarHojaDeRuta()
  }
  
  class "CBO\nChief Brand Officer" as CBO{
    +desarrollarEstrategiaMarca()
    +construirValorDeMarca()
  }
}

package "Organización y talento" {
  class "CHRO\nChief Human Resources Officer" as CHRO{
    +gestionarTalento()
    +desarrollarOrganización()
  }
  
  class "CLO\nChief Learning Officer" as CLO{
    +crearProgramasFormación()
    +desarrollarCompetencias()
  }
  
  class "CPO\nChief People Officer" as CPeopleO{
    +gestionarCultura()
    +fomentarCompromisoEmpleados()
  }
  
  class "CWO\nChief Wellness Officer" as CWO{
    +promoverBienestarEmpleados()
    +equilibrarVidaLaboral()
  }
  
  class "CDIO\nChief Diversity & Inclusion Officer" as CDIO{
    +implementarProgramasDiversidad()
    +promoverIniciativasInclusión()
  }
}

package "Cumplimiento y sostenibilidad" {
  class "CRO\nChief Risk Officer" as CRO{
    +evaluarRiesgos()
    +desarrollarEstrategiasMitigación()
  }
  
  class "CCO\nChief Compliance Officer" as CCompO{
    +asegurarCumplimientoNormativo()
    +gestionarÉticaEmpresarial()
  }
  
  class "CSO\nChief Sustainability Officer" as CSO{
    +definirEstrategiaSostenibilidad()
    +implementarProgramasAmbientales()
  }
  
  class "CEO\nChief Ethics Officer" as CEthicsO{
    +establecerEstándaresÉticos()
    +alinearCultura()
  }
}

package "Innovación y futuro" {
  class "CIO\nChief Innovation Officer" as CInnovO{
    +impulsarEstrategiaInnovación()
    +desarrollarNuevasIniciativas()
  }
  
  class "CKO\nChief Knowledge Officer" as CKO{
    +gestionarConocimiento()
    +desarrollarCapitalIntelectual()
  }
  
  class "CVO\nChief Vision Officer" as CVO{
    +anticiparTendenciasFuturas()
    +definirDirecciónEstratégica()
  }
  
  class "CRO\nChief Remote Officer" as CRemoteO{
    +establecerPolíticasTrabajoRemoto()
    +gestionarEquiposDistribuidos()
  }
  
  class "CAO\nChief Accessibility Officer" as CAccessO{
    +implementarEstándaresAccesibilidad()
    +promoverDiseñoInclusivo()
  }
  
  class "CDO\nChief Design Officer" as CDesignO{
    +definirEstrategiaDiseño()
    +mejorarExperienciaUsuario()
  }
}

' Relaciones jerárquicas
CEO -d-> COO
CEO --> CFO
CEO -d-> CMO
CEO ---> CIO
CEO --> CCO
CEO --> CHRO
CEO --> CInnovO

' Relaciones tecnología
CIO --> CTO
CIO --> CISO
CIO --> CDO
CIO --> CDataO
CIO --> CAO

' Relaciones comunicación
CMO --> CCO
CCO --> CXO
CCO --> CBO
CMO --> CGO
CMO --> CPO

' Relaciones talento
CHRO --> CLO
CHRO --> CPeopleO
CHRO --> CWO
CHRO --> CDIO

' Relaciones cumplimiento
CFO --> CRO
CFO --> CCompO
CEO --> CSO
CSO --> CEthicsO

CInnovO --> CKO
CInnovO --> CVO
COO --> CRemoteO
CDO --> CDesignO
CDIO --> CAccessO

note "Rol emergente enfocado en la\ntransformación digital" as N2
CDO .. N2

note "Rol emergente enfocado en la\nexperiencia del usuario" as N3
CXO .. N3
CDesignO .. N3

note "Reflejo de las nuevas prioridades sociales y culturales" as N4
CDIO .. N4
CSO .. N4
CEthicsO .. N4

note "Especialización reciente, derivado de la pandemia" as N5
CRemoteO .. N5

@enduml