@startuml
hide circle
hide empty members

class "<b>TRANSFORMACIÓN REAL</b>" as TRANSFORMACION {
  equipo
  evaluarProgreso()
  medirImpacto()
  gestionarCambio()
  adaptarEstrategia()
}

package TrianguloDeHierro{

class "TrianguloHierro" as TRIANGULO {
  restricciones[]
  calcularDesviacion()
  ajustarParametros()
  optimizarRecursos()
}

class "Tiempo" as TIEMPO {
  duracionPlanificada
  hitos[]
  fechaInicio
  fechaFin
  calcularRuta()
  actualizarCronograma()
}

class "Coste" as COSTE {
  presupuestoPlanificado
  gastoReal
  distribucionRecursos
  calcularDesviacion()
  gestionarPartidas()
}

class "Alcance" as ALCANCE {
  objetivos[]
  entregables[]
  requisitos[]
  definirLimites()
  gestionarCambios()
}


}

class "Proyecto" as PROYECTO {
  desviacionTiempo
  desviacionPresupuesto
  causasRetraso[]
  calcularDesviacion()
  identificarCausasRaiz()
  implementarMedidasCorrectivas()
  renegociarPlazos()
}

class "Equipo" as EQUIPO {
  miembros[]
  roles[]
  nivel[]
  evaluarCapacidad()
  asignarRoles()
}

class "ROI" as ROI <<difficult>> {
  indicadoresCuantitativos
  beneficiosIntangibles
  metodologiaMedicion
  definirKPIs()
  medirBeneficiosIndirectos()
  calcularROI()
  ajustarMetricas()
}

class "CulturaOrganizacional" as CULTURA {
  nivelResistencia
  gradoAdopcion
  cambiosOrganizativos
  evaluarResistencia()
  gestionarExpectativas()
  promoverAdopcion()
  medirSatisfaccion()
}

class "Competencias" as COMPETENCIAS {
  brechaCompetencias[]
  nuevosRoles[]
  planCapacitacion
  identificarNecesidades()
  desarrollarTalento()
  actualizarPerfiles()
  evaluarDesempeño()
}

TRANSFORMACION *-right- PROYECTO
TRANSFORMACION *-down- ROI
TRANSFORMACION *-down- CULTURA
TRANSFORMACION *-left- COMPETENCIAS
TRANSFORMACION *-down- EQUIPO
EQUIPO ..> COMPETENCIAS

TRIANGULO "1" *-- TIEMPO
TRIANGULO "1" *-- COSTE
TRIANGULO "1" *-- ALCANCE
PROYECTO *-- TRIANGULO : restringido por >


@enduml