hide empty members

abstract Trabajo {
    presentar()
    evaluar()
    documentar()
}

class TrabajoAcademico {
    presentacionVisualElaborada
    estructuraPredeterminada
    requisitosFormales
    listadoParticipantes
    presentar()
    evaluar()
    documentar()
}

class TrabajoProfesional {
    analisisSustancial
    estructuraAdaptativa
    valorReal
    trazabilidadAutomatica
    presentar()
    evaluar()
    documentar()
}

abstract Enfoque {
    tipo
    caracteristicas
}

class EnfoqueAcademico {
    lineal
    teorico
    estandarizado
}

class EnfoqueProfesional {
    iterativo
    practico
    adaptativo
}

abstract Trazabilidad {
    registrarCambios()
    verificarContribuciones()
}

class TrazabilidadAcademica {
    listaEstatica
    autoreporte
    registrarCambios()
    verificarContribuciones()
}

class TrazabilidadProfesional {
    controlVersiones
    historicoContribuciones
    registrarCambios()
    verificarContribuciones()
}

Trabajo <|-- TrabajoAcademico
Trabajo <|-- TrabajoProfesional
Enfoque <|-- EnfoqueAcademico
Enfoque <|-- EnfoqueProfesional
Trazabilidad <|-- TrazabilidadAcademica
Trazabilidad <|-- TrazabilidadProfesional

TrabajoAcademico --> EnfoqueAcademico
TrabajoAcademico --> TrazabilidadAcademica
TrabajoProfesional --> EnfoqueProfesional
TrabajoProfesional --> TrazabilidadProfesional

